netcore.client2/Models/ErrorViewModel.cs
using System;

namespace netcore.client2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

netcore.client2/Models/StaticLocalUsers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace netcore.client2.Models
{
    public static class StaticLocalUsers
    {
        public static List<UserInfo> LocalUsers { get; set; }
        static StaticLocalUsers()
        {
            LocalUsers = new List<UserInfo>
            {
                new UserInfo(){ Name="zhangsan",Password = "123"}
            };
        }
    }
}

netcore.client2/Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace netcore.client2.Models
{
    public class UserInfo
    {
        /// <summary>
        /// 本地名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 本地登录密码
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// 远程名称【为了与本地建立连接】
        /// </summary>
        public string RemoteName { get; set; }
    }
}

netcore.client2/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using netcore.client2.Models;
using Newtonsoft.Json;

namespace netcore.client2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult Login()
        {
            return View();
        }

        public void LocalLogout()
        {
            if (Request.Cookies.TryGetValue("token", out string tokenCookies))
            {
                Response.Cookies.Delete("token");
            }
            if (Request.Cookies.TryGetValue("CurrentUser", out string currentUser))
            {
                Response.Cookies.Delete("CurrentUser");
            }

        }

        /// <summary>
        /// 本地账号密码登录
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        public ActionResult LoalLogin(string userId, string password)
        {
            var localUsers = StaticLocalUsers.LocalUsers;
            var loginUser = localUsers.Find(x => x.Name == userId && x.Password == password);
            if (loginUser != null)
            {
                var json = JsonConvert.SerializeObject(loginUser);
                WriteCookie("CurrentUser", json, DateTime.Now.AddYears(1));
                return Redirect("~/Main/Index");
            }
            return Json("账号密码错误，请重新输入");
        }

        /// <summary>
        /// 远程登录
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public async Task<ActionResult> RemoteLogin()
        {
            //*************代码能进到这里  说明远程完成了登录**********
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            WriteCookie("token", accessToken, DateTime.Now.AddYears(1));
            Console.WriteLine("callback token:" + accessToken);

            var userinfo = GetUserInfoByToken(accessToken);
            WriteCookie("CurrentUser", JsonConvert.SerializeObject(userinfo.Result), DateTime.Now.AddYears(1));

            return Redirect("~/Main/Index");
        }

        /// <summary>
        /// 退出登录
        /// </summary>
        /// <returns></returns>
        public async Task Logout()
        {

            if (Request.Cookies.TryGetValue("token", out string tokenCookies))
            {
                Response.Cookies.Delete("token");
            }
            if (Request.Cookies.TryGetValue("CurrentUser", out string currentUser))
            {
                Response.Cookies.Delete("CurrentUser");
            }

            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }


        /// <summary>
        /// 根据远程TOKEN获取当前用户信息
        /// 有则匹配，无则新增
        /// </summary>
        /// <param name="token"></param>
        /// <returns></returns>
        private async Task<UserInfo> GetUserInfoByToken(string token)
        {
            var dicClient = new DiscoveryClient("http://10.37.11.12:7000");
            dicClient.Policy.RequireHttps = false;
            var doc = await dicClient.GetAsync();

            var userInfoClient = new UserInfoClient(doc.UserInfoEndpoint);
            var userinfoResponse = await userInfoClient.GetAsync(token);
            var claims = userinfoResponse.Claims;

            var userinfo = new UserInfo();
            var remoteName = (claims.FirstOrDefault(x => x.Type == "name") ?? new System.Security.Claims.Claim("name", string.Empty)).Value;
            var localUser = StaticLocalUsers.LocalUsers.Find(x => x.RemoteName == remoteName);
            if (localUser == null && !string.IsNullOrEmpty(remoteName))
            {
                userinfo.Name = remoteName;
                userinfo.Password = "123";
                userinfo.RemoteName = remoteName;
                StaticLocalUsers.LocalUsers.Add(userinfo);//远程用户同步到本地
            }
            else
            {
                userinfo = localUser;
            }
            return userinfo;
        }


        /// <summary>
        /// 为当前请求编写COOKIE
        /// </summary>
        /// <param name="cookieName"></param>
        /// <param name="cookieValue"></param>
        /// <param name="expireTime"></param>
        private void WriteCookie(string cookieName, string cookieValue, DateTime expireTime)
        {
            HttpContext.Response.Cookies.Append(cookieName, cookieValue, new Microsoft.AspNetCore.Http.CookieOptions() { Expires = expireTime });
        }
    }
}

netcore.client2/Controllers/MainController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using netcore.client2.Models;
using Newtonsoft.Json;

namespace netcore.client2.Controllers
{
    //[Authorize]
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            var usercache = Request.Cookies["CurrentUser"].ToString();

            var userInfo = JsonConvert.DeserializeObject<UserInfo>(usercache);
            return View(userInfo);
        }

        [Authorize]
        public async Task<ActionResult> RemoteCallAPI()
        {
            //发起远程调用
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            Console.WriteLine($"access_token:{accessToken}");
            var client = new HttpClient();
            client.SetBearerToken(accessToken);


            //访问netfx对应的identity标识信息
            var netfxUrl = @"http://10.37.11.12:6061/Identity/Get";
            var netfxResponse = await client.GetAsync(netfxUrl);
            var netfxContent = await netfxResponse.Content.ReadAsStringAsync();

            //访问netcore对应的identity标识
            var netcoreUrl = @"http://10.37.11.12:6062/Identity";
            var netcoreResponse = await client.GetAsync(netcoreUrl);
            var netcoreContent = await netcoreResponse.Content.ReadAsStringAsync();

            return Json(new { netfxContent, netcoreContent });
        }
    }
}

netcore.client2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="7000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

netcore.client2/Views/Home/Login.cshtml
@{
    ViewBag.Title = "去登陆";
}

<h2>NETCORE框架登录页面</h2>


<div>
    <form action='@Url.Action("LoalLogin","Home")'>
        <input type="text" name="userId" placeholder="请输入当前站点用户名称" />
        <input type="text" name="password" placeholder="请输入当前站点用户密码" />
        <input type="submit" value="登录"/>
    </form>

    <div>
        <a href="@Url.Action("RemoteLogin","Home")"><span style="color:cadetblue">一键智慧登录</span></a>
    </div>
</div>

netcore.client2/Views/Main/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model netcore.client2.Models.UserInfo

<h2 style="color:red">NETCORE框架下客户端站点【Main】主页</h2>
<h5>当前登录的用户信息如下：</h5>

<p><b><span>本地用户：@Model.Name</span></b></p>

<p><b><span>远程授权服务器：@Model.RemoteName</span></b></p>


<p>
    <a href="@Url.Action("RemoteCallAPI","Main")">调取远程API接口 展示数据</a>
</p>

netcore.client2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - netcore.hybrid.client</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">netcore.hybrid.client</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Main" asp-action="Index">正文信息</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Login">去登陆</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Logout">退出</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="LocalLogout">退出</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - netcore.hybrid.client</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>